### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Johnnywick1** [enesctnn/WeatherApp#1]
Hello,

1. There is no Imperial units button.
2. When you type the name of the city after 3 letter autocomplete is stopping.
3. Is it possible after enter the site geolocation will be automatically recognized? 

Thank you

**Comment by enesctnn** [comment]
> Hello,
> 
> 
> 
> 1. There is no Imperial units button.
> 
> 2. When you type the name of the city after 3 letter autocomplete is stopping.
> 
> 3. Is it possible after enter the site geolocation will be automatically recognized? 
> 
> 
> 
> 
> 
> Thank you

Hello, thank you for your attention. 1. This project is retrieving only metric units for now.
2. There is still autocomplete after 3 words but the npm package is used&called country-state-city is missing place names thats why it seems like that, i tried to fix that with place autocomplete service of google map's and faced with "Access-Control-Allow-Origin" error, unfortunately problem wasn't solved and couldn't replace it. 
3. It is possible that your current location is going to be recognized after you allow to share your location with TypeWeather App and a message will follow to show you your location merged with in a link so you can click and see your current location weather forecast. 
Best regards 
Muhammet Enes Çetin
