### ISSUE TITLE
Some idea

### ISSUE THREAD

**Issue by Johnnywick1** [enesctnn/WeatherApp#2]
Hi,

1. When you enter the website, is it possible for the script to automatically search for a location by IP address? Like here: https://github.com/devalentineomonya/ReactJS-Weather-App or https://github.com/hellishBat/weatherinsight?

When you search cities there is no choice . I mean many cities have the same names. Could you make city, state, country?

Thank you

**Comment by enesctnn** [comment]
### Hi,
  1. I made the geolocation detection is up to user's desicion on purpose.
  2. Now place names are more specific for better results.
  
  I will make two versions for searching geolocation with ip adress and current way.

**Comment by Johnnywick1** [comment]
I know that you made the geolocation detection is up to user's desicion but google doesn't like when the browsers requests the geolocation permission on page load. Read about this here: https://developer.chrome.com/docs/lighthouse/best-practices/geolocation-on-start/?utm_source=lighthouse&utm_medium=lr

What I meant the script automatically find the location without the user's browser permission and  take them to the page with weather forecast like in examples above. If you can make it of course. 

Now search the cities location is better.

Thank you
